### ISSUE TITLE
spout doesn't seem to be working

### ISSUE THREAD

**Issue by DJBunge** [emilianavt/VSeeFaceReleases#10]
I've followed the instructions but VSeeFace is not showing as a Spout Sender in OBS.

**Comment by emilianavt** [comment]
Hi! Spout export is enabled in the general settings in VSeeFace?

**Comment by DJBunge** [comment]
Yes.  ---- On Wed, 09 Feb 2022 05:41:05 -0600  ***@***.***  wrote ----
Hi! Spout export is enabled in the general settings in VSeeFace?

**Comment by emilianavt** [comment]
What GPU are you using? I read that Spout2 might not work on certain GPUs such as some Intel ones.

**Comment by DJBunge** [comment]
I was able to download the SpoutSender / Spout Receiver stand-alone demos and they worked and showed in OBS.I'm using an NVIDIA GeForce GTX 1660 SUPER. ---- On Wed, 09 Feb 2022 10:09:47 -0600  ***@***.***  wrote ----
What GPU are you using? I read that Spout2 might not work on certain GPUs such as some Intel ones.

**Comment by emilianavt** [comment]
That's really odd then.

If you check the [Player.log](https://www.vseeface.icu/#settings-and-log-file-location) file, are there any Spout related errors inside? Do you have a secondary GPU that VSeeFace might be running on for some reason?

**Comment by DJBunge** [comment]
Where would I find Player.log? I don't see a file with that name inside the VSeeFace directory after running it. ---- On Wed, 09 Feb 2022 10:19:34 -0600  ***@***.***  wrote ----
That's really odd then.
If you check the Player.log file, are there any Spout related errors inside? Do you have a secondary GPU that VSeeFace might be running on for some reason?

**Comment by DJBunge** [comment]
It seems like something must have been missing before or I had a different version of a dll.I don't know why it wasn't working,  but it's working now. ---- On Wed, 09 Feb 2022 10:19:34 -0600  ***@***.***  wrote ----
That's really odd then.
If you check the Player.log file, are there any Spout related errors inside? Do you have a secondary GPU that VSeeFace might be running on for some reason?

**Comment by emilianavt** [comment]
Great! I'm glad to hear that it's working now.
