### ISSUE TITLE
Crash on linux while on startup

### ISSUE THREAD

**Issue by vproper** [emilianavt/VSeeFaceReleases#11]
If I try to open VSeeFace on Linux (I tried several Wine versions and none of them work), I get a window with a VSeeFace logo, red square with exclamation mark and a progress bar, after which the program just crashes. What should I do?

**Comment by emilianavt** [comment]
Are you on v1.13.38?

If so, can you try deleting the DLL mentioned at the top here anyways and see if that helps?

https://www.vseeface.icu/#running-on-linux-and-maybe-mac

**Comment by vproper** [comment]
Yes, 1.13.38. I tried older versions, and managed to get 1.13.37 to work without this DLL

**Comment by emilianavt** [comment]
So v1.13.38 with the DLL removed also crashes?

**Comment by vproper** [comment]
Will check that today
