### ISSUE TITLE
Feature Request: Allow Avatar Root Transforms Via Animations

### ISSUE THREAD

**Issue by VinTechage** [emilianavt/VSeeFaceReleases#12]
I've made animation clips for an avatar where their legs stretch. However, I want the avatar to move up when his legs extend rather than his legs pushing down. I've tried applying animation transforms to the root, and it does not apply it in VSeeFace. I've also tried doing the same process to the pelvis bone. Even when transformed upward, the spine bends downward instead of staying up straight (even with rotation constraints applied). I would like if we can change our avatar's root position using animation clips.

**Comment by emilianavt** [comment]
Hi!

Root transforms should work, but you will have to tick the "disable IK" box, which will also prevent any tracked movement from being applied to the model. Otherwise, the IK, which acts outside the animation system, will overwrite it according to the tracked head position.

**Comment by VinTechage** [comment]
> Hi!
> 
> Root transforms should work, but you will have to tick the "disable IK" box, which will also prevent any tracked movement from being applied to the model. Otherwise, the IK, which acts outside the animation system, will overwrite it according to the tracked head position.

I see. However, is there any way to achieve root translations without disabling the IK system? Disabling the IK system for these animations will severely limit user interactivity for the purposes of this avatar.

**Comment by emilianavt** [comment]
The IK will always adapt the pose of the model to the head target, which will not move along with the animation, so it's not really possible.
