### ISSUE TITLE
NetWorkTracking Gaze Non-Functional

### ISSUE THREAD

**Issue by PhamtomWolf** [emilianavt/VSeeFaceReleases#13]
I use NetWorkTracking to offload work to a second machine for 2 reasons, minimize CPU usage overall as well as make it utterly impossible to DOX myself

My issue is that Gaze tracking does not work no matter what i do...

So i have a simple question and im assuming the answer is no so here is the question

Does VMC Protocol support Gaze Tracking?

If it does then i honestly have no idea what i have or am doing wrong

If no then it would be useful to mention that Gaze Tracking doesn't work with Network tracking

**Comment by emilianavt** [comment]
Gaze tracking is supported over both network tracking and VMC protocol. A few things to check:

* Ensure that the tracking quality is not set to toaster mode. Older versions of VSeeFace have a bug where having the tracking quality set to that will also affect the network tracking options.
* Try turning gaze sensitivity and gaze strength all the way up.
* Test it with the [Vita](https://www.vseeface.icu/Vita.vrm) model, to ensure it is not a model issue.

**Comment by PhamtomWolf** [comment]
Ok, I managed to figure out what was wrong...

I had enabled fake gaze originally when I switched to network tracking because gaze tracking was not working on whichever version that was, but recently decided to try to get it working and I did, disabling fake gaze made it work just fine... kinda...

I use my phone for tracking so it is placed below my monitor and looks up at me at about 60 degrees (that is 60 degrees as read on a protractor, so 30 degrees tilted backwards)

so my eyeballs kinda disappear inside my head unless I put the strength down but doing that makes the gaze happen slower rather than happen at a reduced distance... (would be nice if there was a gaze offset that allowed you to move your gaze up and down to compensate for camera angle)

so for the current version, I have found a happy medium between slow and not looking like I have been possessed

Absolutely love the work you are doing for the Vtubing community and thank you

**Comment by emilianavt** [comment]
There is actually a gaze offset option, but it has to be enabled from the advanced settings. A lot of people used to misconfigure it by accident, so I had to hide it away a bit.

**Comment by PhamtomWolf** [comment]
Ok yeah i have found it, thank you so much for the help and for creating multiple amazing tools for us to use, more so VSeeFace and OpenSeeFace

**Comment by emilianavt** [comment]
I'm glad you like them!
