### ISSUE TITLE
[Linux, Wine] Camera Controls Not working

### ISSUE THREAD

**Issue by VinTechage** [emilianavt/VSeeFaceReleases#14]
I've managed to get VSeeFace to work on Wine on Linux. Unfortunately, the camera controls to manipulate the camera in VSeeFace don't work. I can't rotate the camera or zoom inwards. I can zoom outwards and pan the camera, but that's it. Is there a way to fix this problem?

VSeeFace: v1.13.38
Wine Version: lutris-fshack-6.21-6-x86_64 (default)
OS: Arch Linux (Kernel Version - 5.17)

**Comment by emilianavt** [comment]
Perhaps something is preventing the pressed alt key from being signalled to the window correctly? There isn't really anything platform specific about the camera handling, so as long as mouse and keyboard controls are processed correctly, it should work.

**Comment by VinTechage** [comment]
> Perhaps something is preventing the pressed alt key from being signalled to the window correctly? There isn't really anything platform specific about the camera handling, so as long as mouse and keyboard controls are processed correctly, it should work.

Alt + MMB works. I don't know why the other movements that require ALT don't work.

**Comment by emilianavt** [comment]
Could they be already be in use by your window manager for functionality like resizing or moving windows?

**Comment by VinTechage** [comment]
> Could they be already be in use by your window manager for functionality like resizing or moving windows?

I did some research and turns out that the 'alt' key in linux desktop environments is the default for moving windows. I changed it to 'hyper', and now it works.

**Comment by emilianavt** [comment]
Great, I'm glad you got it working!
