### ISSUE TITLE
[Linux / Wine] VSeeFace not working at all since VSeeFace v1.13.37c

### ISSUE THREAD

**Issue by TomCoursow** [emilianavt/VSeeFaceReleases#16]
Hi,

I noticed that VSeeFace is not working with wine anymore at all...
It stopped working at Version **v1.13.37c**
(so also current version is broken)

The app want to open and shows the Unity Screen for a moment...
After that an error is thrown:
![image](https://user-images.githubusercontent.com/17900090/173879869-9c35c85c-016b-4677-b473-3eab4b58002f.png)

**Crash Report (Error.log):**
[error.log](https://github.com/emilianavt/VSeeFaceReleases/files/8911445/error.log)

**Player.log:**
[Player.log](https://github.com/emilianavt/VSeeFaceReleases/files/8911481/Player.log)

Lutris / Wine Log:
https://pastebin.com/JgwHaFRw

Is that a known issue?
Maybe it helps and I hope that somehow it will work in the future with wine again.
So for now I will keep one of the older versions^^

Best regards,
Tom

**Comment by emilianavt** [comment]
Hi, it's a known issue. Please follow the workaround described here for now:

https://www.vseeface.icu/#running-on-linux-and-maybe-mac

**Comment by TomCoursow** [comment]
@emilianavt 
Oh my god... I realy red that article about 3 times or more... Never noticing... the **fat printed** GPUManagementPlugin.dll part... Sorry

**Comment by TomCoursow** [comment]
@emilianavt 
Are locally downloaded .vrm models from VRoid Hub supported?
Seems that my own vroid character created with Vroid studio as well as downloaded vrm files do not Load when I click Start in VSeeFace...
![image](https://user-images.githubusercontent.com/17900090/173936374-3ed56697-aeb3-4c3c-a27f-7fd825b2e2bc.png)
