### ISSUE TITLE
Request: Flatpack version of VSeeFace 

### ISSUE THREAD

**Issue by Supermagnum** [emilianavt/VSeeFaceReleases#17]
Hello, since the newer versions don't seem to work on Linux, it's necessary to use a old version ( 1.13.37b )

The transparency will most likely not work with that so a background and green screen needs to be added it.

The solution for that is to release a flatpack version, as it makes it possible and easy to run VSeeFace on any given version of Linux.

Flatpack and documentation can be found here:
https://www.flatpak.org/

**Comment by emilianavt** [comment]
Hi, the current version works fine. Just make sure to follow the note at the beginning of this section:

https://www.vseeface.icu/#running-on-linux-and-maybe-mac

Setting a background color is also already supported on Linux and documented in that section.

**Comment by Supermagnum** [comment]
> Hi, the current version works fine. Just make sure to follow the note at the beginning of this section:
> 
> https://www.vseeface.icu/#running-on-linux-and-maybe-mac
> 
> Setting a background color is also already supported on Linux and documented in that section.

It goes so far that the avatar shows,- then its crashes.

GPUManagementPlugin.dll has been deleted.

Backtrace/log: https://pastebin.com/MEkgM09X

winetricks -q vcrun2015 fixed it.

**Comment by emilianavt** [comment]
Thank you. I'll add that as a requirement on the website.

Edit: Done.
