### ISSUE TITLE
A question about VseeFace and transparency in obs for linux

### ISSUE THREAD

**Issue by Supermagnum** [emilianavt/VSeeFaceReleases#20]
Hello,  according to the Internets it is possible to get VseeFace to run under wine, with a green background that can be removed with chromakey using:
Wine VSeeFace.exe --background-colour #00ff00 .
I have tried that,-without any luck.

There also is no virtual camera support in wine, and no game capture mode in OBS for linux

**Comment by emilianavt** [comment]
Please refer to this section of the website for details: https://www.vseeface.icu/#running-on-linux-and-maybe-mac
