### ISSUE TITLE
Investigation into support for EasyVirtualMotionCaptureForUnity?

### ISSUE THREAD

**Issue by grofit** [emilianavt/VSeeFaceReleases#22]
Hi there, not sure if this is the right repository to post in but I was testing out another application which does the same sort of thing as VSeeFace but under the hood seems to use [EasyVirtualMotionCaptureForUnity](https://github.com/gpsnmeajp/EasyVirtualMotionCaptureForUnity) for pretty good results with hand/finger/arm tracking with just a webcam.

Given that VSeeFace is built on Unity and this other library runs within Unity is there any possibility for an investigation into seeing if this can be added as an optional plugin/option to be supported as at the moment im having to pipe a virtual camera to the other app to get arm/hand/finger tracking then pipe that over VMC into VSeeFace, but it seems like VSeeFace could just natively support this and remove the need for the additional app hopping.

No worries if this is not of interest but having used it I was very surprised at how good the tracking was even with a SUPER cheap webcam.

**Comment by emilianavt** [comment]
Hi!

EVMC4U is a library used to receive VMC protocol tracking data and apply it to a model. VSeeFace actually uses it as part of its VMC protocol receiver functionality. It's not a tracking library on its own though.

I'm not really looking to add new tracking libraries currently, but many of the more interesting tracking programs can already send the avatar animation data over VMC protocol to VSeeFace, so it's possible to use the programs together.

**Comment by grofit** [comment]
Oh sorry thats a misunderstanding from my point, I was lead to believe that WAS the tracking + training data not just a protocol. I currently do as you mention and pipe output from one app to VSeeFace but was hoping there was a way to streamline it further.

Anyway sorry to have wasted your time.
