### ISSUE TITLE
[Question] Is there any plan to support Sony mocoppi?

### ISSUE THREAD

**Issue by dokdo2005** [emilianavt/VSeeFaceReleases#23]
[https://www.sony.jp/mocopi/](url)

Since the SDK of Sony mocopi is going to be released around December 15th, is there any plan to support this SDK?

**Comment by emilianavt** [comment]
It will depend on the SDK (how it works and licensing). From what I heard, mocopi might support VMC protocol out of the box, in which case it could be used with VSeeFace directly.
