### ISSUE TITLE
High resource usage even when avatar is off

### ISSUE THREAD

**Issue by tomaae** [emilianavt/VSeeFaceReleases#24]
Hi,
There are several issues with both high CPU and GPU usage when avatar is off. Meaning I'm using tracking with VMC output only.
CPU usage can go to 12-15% on 12700 cpu. Interesting is that when I open general settings and leave it open, it will drop to around 4%.
GPU usage is around 15% on rtx3700 with avatar off. This is unreasonable as it only should render menus.
All this was tested during stream, so GPU was in high power mode. CPU is always at high power.

Also small thing, "less mesh updates" is not saved over sessions.

**Comment by emilianavt** [comment]
> CPU usage can go to 12-15% on 12700 cpu.

Are you using webcam tracking? For me, the webcam tracking takes about 10% CPU, while the VSeeFace UI itself takes about 2%. On a 1080, with avatar rendering it used 8-10% GPU for me. I made a video [here](https://www.youtube.com/watch?v=hBxMBvH069s).

> Interesting is that when I open general settings and leave it open, it will drop to around 4%. GPU usage is around 15% on rtx3700 with avatar off. This is unreasonable as it only should render menus.

Are these measurements with no other heavy programs running? In that case, it could be that the CPU and GPU are clocked down to save power, making the percentages look higher. That might also explain why the CPU usage drops with the menu open. Perhaps it causes it to clock up.

> less mesh updates

This option is mainly a debugging aid and can cause problems when rendering avatars so it does not get saved.

**Comment by tomaae** [comment]
yea, I use webcam, arkit and leapmotion.

it was all measured during streaming, my total cpu and gpu were both at around 90% . so no powersafe

less mesh updates actually lowers the load even when avatar is off. that and high gpu load makes me believe it is still being rendered, just not being visible, or offscreen.

**Comment by emilianavt** [comment]
That's very strange then. It definitely doesn't get rendered. The option to disable avatar rendering disables the game object in Unity. You can try exporting a model with all the meshes removed and compare to that.

The only thing I can imagine is that perhaps the preview for the avatar selection still gets rendered. In that case, adding [this cube](https://www.vseeface.icu/Cube.vrm) and selecting it (without actually loading it as the avatar) might help. If it does, that's something I need to look into fixing.

Another thing you can try is lowering the frame rate cap in VSeeFace's general settings. If the receiving application interpolates the VMC protocol data properly, lowering it to 30 might be fine.

**Comment by tomaae** [comment]
I'm not sure that just disabling it at tree will stop render in unity. I remember running into such issues during map creation.

If I change avatar to anything different, tracking will be weird. Not sure why is that.

I use cap of 45, which matches my render rate. Disabled AA and all graphical options.

**Comment by emilianavt** [comment]
Disabling it definitely stops rendering.

You can just select the avatar in the avatar switcher so the preview camera focuses on the cube instead of your regular model for testing. You don't need to actually load it.

**Comment by tomaae** [comment]
ok, so I solved GPU utilization issues. its now at ~0.3% in normal use. Dont ask how, I reinstalled my OS from scratch. Something weird must have been broken deep in. It solved some other GPU glitches I had, so I guess it was for the best.

But CPU goes to 20% often. Thats way too much on 12700, games dont usually use that much CPU. on my old 8770k it was about 8%.
I will try to install bunch of older VSF versions, maybe I will find out more pointers.

Edit: Selecting cube in avatar selection will make CPU usage go down for a bit without any effect on tracking. But it will climb up again.

**Comment by emilianavt** [comment]
Webcam tracking can be quite heavy, especially at higher camera frame rates. Often lowering the webcam FPS to 15 (if the actual tracking rate is higher) can reduce it quite a bit. There's some more information here: https://www.vseeface.icu/#cpu

The Leap Motion tracking service also can use quite a bit of CPU, especially with both hands in view.

**Comment by tomaae** [comment]
I use 800x448 30fps YUY2
Barely okey quality tracking option, since I only use camera for head tracking. face tracking uses ifacialmocap.

facetracker rarely go above 3%. it usually sits under 1%, rest is vseeface main process.

We are talking about 20% of modern powerful 12 core CPU. My old 8770k would not be even capable to provide that much CPU power, but it was still able to with about 10% usage using same settings and tracking hardware.
I didnt even changed my model, everything is the same.

As a side note, friend who has exactly same motherboard and cpu and also uses same tracking method and settings has average 7% usage. Except he also has avatar on, AA and everything on.
Still bit high for this CPU, but I would be okey with that.

I understand that such issue can be difficult to find, but I dont even have idea where to look now.

**Comment by emilianavt** [comment]
I honestly have no idea how the facetracker could possibly be at 3% while VSeeFace is at 20%. It doesn't even really use much threading, so it should at most use one core. For me, VSeeFace itself with the tracker excluded usually sits at 4% at 1280x720, 60 fps on a 16 core AMD CPU (Zen+).

**Comment by tomaae** [comment]
yup, I would expect 4-6%.
is there any way to debug what is going on? maybe GPA profiling could give some hints?

**Comment by emilianavt** [comment]
I could make a development build with profiling enabled when I find some time.

I just thought of one thing though. Could you please take a look at the [Player.log](https://www.vseeface.icu/#settings-and-log-file-location) and see if it's getting spammed with some kind of exception? I think that happened before once.

**Comment by tomaae** [comment]
Sure, I have no problem waiting :)

Yes, it is getting spammed. Here is complete log:
[Player.log](https://github.com/emilianavt/VSeeFaceReleases/files/10420326/Player.log)

**Comment by emilianavt** [comment]
Interesting, that's something I haven't seen before. It's throwing an exception in the eye blink code. How's your CPU load if you use [Vita](https://www.vseeface.icu/Vita.vrm) as the model?

**Comment by tomaae** [comment]
I'm getting same errors with vita model.
Hovewer, vita is not compatible with my model, vsf wont even forward ARKIT blendshapes via VMC and sizes are completly off. So its not something I can properly test live. I will try to simulate something, but will it have any value if does not process same data?
Quick A/B testing shows significantly less CPU and GPU usage, but I need to run it at least for 2 hours in normal load to get any reliable data.

**Comment by tomaae** [comment]
Ok, so for testing, I run my stream setup as usual. But OBS is set to bandwidth testing mode, so I can stream data too without going live.
At first, it started like this and was stable for a while:
![image](https://user-images.githubusercontent.com/23486452/212750755-511fd830-991d-43de-a7db-17219aad1800.png)

After a while:
![image](https://user-images.githubusercontent.com/23486452/212747842-855ba684-f558-4a4a-8eb9-4aae33ea2194.png)

Not sure why there is crash handler in some instances.
Interesting is, that it can run fine with 1% utilization perfectly fine. Seen even 0.4% for a while.
Not sure if facetracker was acting like this all the time or just during last test. Before, I used to monitor main process only.

It could be related to vsf not being compatible with new CPU scheduler tho. By manually setting up affinity to only P cores, I'm getting much more consistant performance, usually around 4% for all of vsf processes.

**Comment by emilianavt** [comment]
> I'm getting same errors with vita model.

The exception in the EyeBlink function? Now that is extremely weird. I'm not sure what to make of it and will have to take a look at the code.

**Comment by tomaae** [comment]
My full settings:
![image](https://user-images.githubusercontent.com/23486452/213021343-a4d7176f-e335-4138-8c0a-480e923db88c.png)
![image](https://user-images.githubusercontent.com/23486452/213021366-02ea00f2-e91b-42f4-9a06-dbb83aed5688.png)
![image](https://user-images.githubusercontent.com/23486452/213021387-5cf7f945-5987-466b-85fd-b4e0cd60ec05.png)
![image](https://user-images.githubusercontent.com/23486452/213021419-869de9e5-c358-4a9e-b37c-b2d4d0986d88.png)
![image](https://user-images.githubusercontent.com/23486452/213021439-88a07d0b-8aa3-4040-a4ba-c141acc77c78.png)

**Comment by emilianavt** [comment]
Can you please confirm whether the Vita model throws the exception in EyeBlink specifically, or just does log spam in general?

**Comment by tomaae** [comment]
> 

ah yes, same eyeblink expection.
