### ISSUE TITLE
Using the winehq repositories may cause a issue. 

### ISSUE THREAD

**Issue by Supermagnum** [emilianavt/VSeeFaceReleases#26]
Using the winehq repositories, and the tracking portion of Vseeface does not work. I have tried two different commands to run vseeface.

wine --version
wine-8.0.1

Vseeface version 1.13.38c2:

Pastebin with logs and information:
https://pastebin.com/x7bzxThM

I have tried to contact the wine support by IRC, waited a hour without any response. 

I will purge the winehq repository and software from the mentioned repository and try with the wine version that is in the official linux mint repositories, because I remember that it worked.

**Comment by emilianavt** [comment]
I can't really do anything about the latest wine version having issues with VSeeFace. You can try reporting them on the WineHQ forums. There seem to be some previous discussions about VSeeFace issues as well.
