### ISSUE TITLE
[Feature request] tobii aye support

### ISSUE THREAD

**Issue by nexioss** [emilianavt/VSeeFaceReleases#32]
well,
not everyone have an iphone,
but i have a tobii aye, and i was wondering if any support for it yould be possible, or even on the way.

thanks in advence

**Comment by emilianavt2** [comment]
Please see here: https://www.vseeface.icu/#does-vseeface-support-the-tobii-eye-tracker

**Comment by nexioss** [comment]
aw, sad, but thanks anyway
