### ISSUE TITLE
1.13.38c starts, but empty menus on ubuntu 22.04

### ISSUE THREAD

**Issue by j2l** [emilianavt/VSeeFaceReleases#33]
Hello,
As you can see, text is not showing up for me.
I'm using Pop!_OS 22 LTS (`Linux pop-os 6.4.6-76060406-generic #202307241739~1695312586~22.04~4d8f3e9 SMP PREEMPT_DYNAMIC Thu S x86_64 x86_64 x86_64 GNU/Linux`) with `wine-6.0.3 (Ubuntu 6.0.3~repack-1`). CPU is intel, GPU RTX3060
![image](https://github.com/emilianavt/VSeeFaceReleases/assets/65325/13876bff-353c-49a5-8229-af0c1c0d22de)

I double check in Q4wine > wineconfig, everything seems to be default.
Any idea how to fix it?
Thank you for your time.

**Comment by emilianavt2** [comment]
Please install Arial.ttf as described [here](https://www.vseeface.icu/#running-on-linux-and-maybe-mac).

**Comment by j2l** [comment]
Thank you very much @emilianavt2 
My bad, I should have read it completely.
