### ISSUE TITLE
apply Movement Smoothing to VMC input

### ISSUE THREAD

**Issue by Kalimocho** [emilianavt/VSeeFaceReleases#37]
Movement Smoothing doesn't apply to movement received by VMC . Is there any option to activate that?

**Comment by emilianavt** [comment]
Please use the VMC protocol receiver's bone smoothing option.

**Comment by Kalimocho** [comment]
Thanks a lot, i can't belive i missed that option. Are there any plans for updating VseeFace? I see you work on OpenSeeFace too. is it there any discord for discussions, giving feedback, maybe i can give help? ty!!
