### ISSUE TITLE
huge log file

### ISSUE THREAD

**Issue by ChildoftheBeast** [emilianavt/VSeeFaceReleases#4]
I woke up this morning to no disk space and a 200GB log file for VSeeFace.
This might be a me issue since i have it open in the background all the time. But added some kind of log management to make sure someone doesn't end up with huge log sizes would be very well appreciated.

![LogSize](https://cdn.discordapp.com/attachments/883838895618420866/901253151762558996/unknown.png)

i was using version 1.13.36k

**Comment by emilianavt** [comment]
That's crazy! I wonder how it happened. It shouldn't really grow much at all usually. Could you try upgrading to the latest version and keep a watch on it while shortly running VSeeFace? If it grows quickly, perhaps you could grab a sample while it's still small so that I can see what is causing the log spam.

**Comment by ChildoftheBeast** [comment]
will do!
i should have tried saving it but i was more focused on reclaiming my diskspace. doubt i could have even opened it.

**Comment by emilianavt** [comment]
That's definitely understandable! Handling files of that size is usually a bit tricky.

**Comment by ChildoftheBeast** [comment]
it was open for ~8 days
so i'll get back to you in 8 days or sooner if the log file goes over 1 gig

**Comment by emilianavt** [comment]
It really shouldn't get bigger than a few hundred KB at any time, so if it does, please let me know.

**Comment by ChildoftheBeast** [comment]
i think this could be it
```
Speeding detected. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```
*above file doesn't exist on my system*

that is being spamming in the log, file size has climbed to 600kb in roughly a day.
actually i just saw it climb ~20kb in about 2 min

i am still on `1.13.36k` right now, i want to see if it happens again before updating, so i know what to look for

edit:
after doing some half paying attention math, 10kb/min in 8 days should be roughly 200mb so it might be something else.

**Comment by emilianavt** [comment]
That's very interesting. I can just make sure that option doesn't get output more than 100 times or something like that. It's output when the frame rate is found to be higher than the frame rate cap set in the general options. I wonder why that is happening in your case.

**Comment by ChildoftheBeast** [comment]
I'm going to update to `1.13.36o`
I'll reopen this if it starts spamming with something else, since I'm not quite sure it was the speeding log that did that. It defiantly didn't help but I don't think it was the issue because the math didn't work out for how long it was open for.
very strange. Thank you for looking at it though and getting the speeding spam fixed. Appreciate it!

**Comment by ChildoftheBeast** [comment]
oh, i forgot to add.
If you want to help troubshoot why the speeding was happening and see if it's a bug, feel free to add me on discord. i'll help in any way i can.
i have a weird PC setup, so it could be something hardware related? not sure, never knew this could be an issue.
BeastChild#0666

**Comment by emilianavt** [comment]
The speeding issue probably isn't harmful. It might be just a graphics driver setting or something similar unlocking the frame rate.
