### ISSUE TITLE
Why closed source?

### ISSUE THREAD

**Issue by viasux** [emilianavt/VSeeFaceReleases#6]
If the program is both free for commercial and non-commercial use, why keep the code closed source? Why only release some of the code? If you're worried about some company using it for commercial purposes, why not release it under a copyleft license?

**Comment by blackorbit1** [comment]
It could also be made public under a copyright licence so no one else would be able to distribute the software but the code could be public and everyone could be able contribute to it.

**Comment by emilianavt** [comment]
It uses proprietary assets from the Unity asset store. I could in theory release a repository with all those dependencies removed so people who feel like buying them themselves could build their own version, but keeping a separate repository for that up to date would just mean extra work for me. It's also my personal feeling that I just simply don't want to make it open source.
