### ISSUE TITLE
Release v1.13.37c break Wine compatibility

### ISSUE THREAD

**Issue by Emily9121** [emilianavt/VSeeFaceReleases#9]
Hello

It might be my mistake, but I believe not, so I think this version broke Wine compatibility - every previous version I tried including V1.13.37b start just fine, but this last release hang up when doing the initial loading.

![Loading](https://user-images.githubusercontent.com/11044962/152703567-1f6fd98e-876a-4b40-8967-43cc73b5aeeb.png)

Then I see in the logs

`wine: Call from 000000007BC31D28 to unimplemented function GDI32.dll.D3DKMTSetProcessSchedulingPriorityClass, aborting
wine: Unimplemented function GDI32.dll.D3DKMTSetProcessSchedulingPriorityClass called at address 000000007BC31D28 (thread 00f4), starting debugger...
Initial process has exited (return code: 256)
`

Attempted with Wine 7.1 and Wine 6.21-6, both x86_64

Thanks,
Emily

**Comment by emilianavt** [comment]
Hi!

It's a known issue and will be fixed. I posted a workaround on the website some time ago. You can find it in the "running on linux" section.

**Comment by Emily9121** [comment]
Can confirm the workaround work, I somehow missed it during my first read, sorry!
